# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_beer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='overall',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
